jwtSignatureSecret: o5KnhuFU8q8bo6qPxG2Z75q3yLlNiVCSOUd0vqbv6X8E8QLUSbP6Uxn7hn2678NZ3sQ1ZKy9ih7jAHXu

# Database settings.
database:

    # the name of your JDBC driver
    driverClass: com.mysql.jdbc.Driver

    # the username
    user: ${MYSQL_ROOT_USERNAME}

    # the password
    password: ${MYSQL_ROOT_PASSWORD}

    # the JDBC URL
    url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/${MYSQL_DB_NAME}?createDatabaseIfNotExist=true

    # The initial size of the connection pool.
    initialSize: 2

    # The minimum size of the connection pool.
    minSize : 2

    # The maximum size of the connection pool.
    maxSize : 8

# Enable HTTPS
server:
    applicationConnectors:
        - type: http
          port: 8080
        - type: https
          port: 8443
          keyStorePath: ${KEYSTORE_FILE}
          keyStorePassword: ${KEYSTORE_PASSWORD}
          validateCerts: false
          validatePeers: false

#Jersey client settings
jerseyClient:
    #The maximum idle time for a connection, once established.
    timeout: 1000ms
    #The size of the work queue of the pool used for asynchronous requests.
    #Additional threads will be spawn only if the queue is reached its maximum size.
    workQueueSize: 16
# CORS settings
#   A list of comma-separated domains that the service will allow cross-origin access from.  If the Origin matches one
#     of the domains in the list the application will generate a matching Access-Control-Allow-Origin header in the response.
#     If the Origin header does not match, the application will not send the A-C-A-O header back to the client.
#   Uses Jetty's CrossOriginFilter, so partial regex is supported:
#     i.e. https?://*.cgi.[a-z]{3}   -> supports http/https with any subdomain and any 3 character top-level domain for the host "cgi"
#   c.f. https://www.eclipse.org/jetty/documentation/9.3.x/cross-origin-filter.html
# IMPORTANT NOTE: if there is no * character in the expression, the filter processes it as a raw string, NOT as a regex
cors:
  allowedDomains: https?://*.cgi.[a-z]{3},https?://*.cgi.[a-z]{3}:[0-9]{4},http://localhost:9000,http://localhost:8000,https?://(192.168).*.*:[0-9]{4},https?://(10.1).*.*:[0-9]{4}
  allowedHeaders:
   - Accept
   - Authorization
   - Content-Length
   - Content-Type
   - Content-Disposition
   - Cookie
   - Origin
   - Referer
   - x-amz-date
   - x-api-key
   - x-requested-by
   - x-requested-with

mapsApi:
  apiURL: http://maps.googleapis.com/maps/api/geocode/json
  apiKey: <your_key>

# Notification mail settings.
mail:

   #The host running the SMTP server to use. 
  hostname: "smtp.gmail.com"

   #The port at which the SMTP server listens on. 
  port: 587

   #The address used as From for outgoing notification mails sent by the server.
  systemEmail: "someuser@gmail.com"

   #The username used to access the mail server.
  username: "someuser"

   #The password used to access the mail server.
  password: "somepass"
  
   #Connect using SSL.
  ssl: true
  
   #Connect using TLS.
  tls: true

# Logging settings
logging:
  level: INFO
  loggers:
    com.cgi: DEBUG

# Swagger settings
swagger:
  resourcePackage: com.cgi.poc.dw.rest.resource

twilio:
  accountSID: AC911b35928f09f10ffa8e544127a22016
  authToken: dc093bd56e75d4897a2fac1f374578ca
  phoneNumber: +19162490778
